# Generated by Django 3.2 on 2025-07-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='telephono_number',
            new_name='telephone_number',
        ),
    ]
