# Generated by Django 3.2 on 2025-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_telephono_number_order_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('No procesado', 'Not Processed'), ('Procesado', 'Processed'), ('Enviado', 'Shipping'), ('Entregado', 'Delivered'), ('Cancelado', 'Cancelled')], default='No procesado', max_length=50),
        ),
    ]
