# Generated by Django 3.2 on 2025-07-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorcentageCoupon',
            new_name='PercentageCoupon',
        ),
        migrations.RenameField(
            model_name='percentagecoupon',
            old_name='discount_porcentage',
            new_name='discount_percentage',
        ),
    ]
